In [1]:
#Standard Imports
import numpy as np
import re
import string
import pandas as pd
import random

In [ ]:
#load data
#Data nova_2 is actual text output from Deepgram Nova-2 merged with the file name,
#Dummy columns include student name, ID, email, and case (merged from SimulationIQ data)

In [14]:
data_simIQ=pd.read_csv("AI Classification Data Formatted.csv", usecols=['ID','Organization Unit','Case/Scenario Name'],header=0)
data_simIQ= data_simIQ.sample(154).reset_index(drop=True) #randomly select 154 students
nova_2 = pd.read_csv("nova 2 transcriptions Final.csv", header=None)

In [3]:
data_simIQ

    Organization Unit           ID                      Case/Scenario Name
0              Auburn  Student.212           Acute Viral Myocarditis I51.4
1            Virginia  Student.105           Ischemic Cardiomyopathy I25.2
2              Auburn  Student.267           Acute Viral Myocarditis I51.4
3              Monroe  Student.561  Fam. Hypertrophic Cardiomyopathy I42.2
4           Carolinas  Student.479           Ischemic Cardiomyopathy I25.2
..                ...          ...                                     ...
149            Auburn  Student.298  Fam. Hypertrophic Cardiomyopathy I42.2
150         Carolinas  Student.375  Fam. Hypertrophic Cardiomyopathy I42.2
151         Carolinas  Student.390           Acute Viral Myocarditis I51.4
152            Monroe  Student.543           Acute Viral Myocarditis I51.4
153            Monroe  Student.600           Acute Viral Myocarditis I51.4

[154 rows x 3 columns]

In [15]:
column_to_move =data_simIQ.pop("ID")
data_simIQ.insert(1, "Student Name", column_to_move)

In [16]:
data_simIQ['Presentation']=nova_2
data_simIQ['ID'] = random.sample(range(1, 1000), 154)
data_simIQ['Email'] = data_simIQ['Student Name'] + '@vcom.edu'

In [17]:
data_simIQ['ICD10'] = data_simIQ['Case/Scenario Name'].str.rsplit(' ',1).str[-1]
data_simIQ['Case/Scenario Name']=data_simIQ['Case/Scenario Name'].str.rsplit(' ',1).str[0]
data_simIQ

,Organization Unit,Student Name,Case/Scenario Name,Presentation,ID,Email,ICD10
0,Auburn,Student.206,Fam. Hypertrophic Cardiomyopathy,Mrs. Palmer is a 62 year old female presenting...,17,Student.206@vcom.edu,I42.2
1,Carolinas,Student.460,Ischemic Cardiomyopathy,"Hi, doctor Rollins. I just saw miss Palmer in ...",477,Student.460@vcom.edu,I25.2
2,Virginia,Student.84,Ischemic Cardiomyopathy,"Today with shortness of breath and, fatigue. S...",546,Student.84@vcom.edu,I25.2
3,Carolinas,Student.478,Fam. Hypertrophic Cardiomyopathy,"Mister Leslie Palmer, who is a 62 year old mal...",948,Student.478@vcom.edu,I42.2
4,Auburn,Student.275,Sarcoidosis R. Cardiomyopathy,Good morning. Miss Palmer is a 60 year old 62 ...,631,Student.275@vcom.edu,I42.5
...,...,...,...,...,...,...,...
149,Auburn,Student.293,Fam. Hypertrophic Cardiomyopathy,2 year old male presents to the emergency depa...,132,Student.293@vcom.edu,I42.2
150,Virginia,Student.120,Ischemic Cardiomyopathy,She's a 62 year old female who presents to the...,183,Student.120@vcom.edu,I25.2
151,Auburn,Student.224,Ischemic Cardiomyopathy,Missus Leslie is a 62 year old female patient ...,976,Student.224@vcom.edu,I25.2
152,Carolinas,Student.404,Acute Viral Myocarditis,So I just met with Leslie Palmer. She is a 62 ...,67,Student.404@vcom.edu,I51.4
153,Virginia,Student.43,Acute Viral Myocarditis,"Palmer. Patient presents with, shortness of br...",806,Student.43@vcom.edu,I51.4

In [18]:
column_to_move =data_simIQ.pop("ID")
data_simIQ.insert(0, "ID", column_to_move)
column_to_move =data_simIQ.pop("Email")
data_simIQ.insert(3, "Email", column_to_move)
column_to_move =data_simIQ.pop("Organization Unit")
data_simIQ.insert(3, "Organization Unit", column_to_move)
column_to_move =data_simIQ.pop("ICD10")
data_simIQ.insert(5, "ICD10", column_to_move)

In [19]:
data_simIQ

,ID,Student Name,Email,Organization Unit,Case/Scenario Name,ICD10,Presentation
0,17,Student.206,Student.206@vcom.edu,Auburn,Fam. Hypertrophic Cardiomyopathy,I42.2,Mrs. Palmer is a 62 year old female presenting...
1,477,Student.460,Student.460@vcom.edu,Carolinas,Ischemic Cardiomyopathy,I25.2,"Hi, doctor Rollins. I just saw miss Palmer in ..."
2,546,Student.84,Student.84@vcom.edu,Virginia,Ischemic Cardiomyopathy,I25.2,"Today with shortness of breath and, fatigue. S..."
3,948,Student.478,Student.478@vcom.edu,Carolinas,Fam. Hypertrophic Cardiomyopathy,I42.2,"Mister Leslie Palmer, who is a 62 year old mal..."
4,631,Student.275,Student.275@vcom.edu,Auburn,Sarcoidosis R. Cardiomyopathy,I42.5,Good morning. Miss Palmer is a 60 year old 62 ...
...,...,...,...,...,...,...,...
149,132,Student.293,Student.293@vcom.edu,Auburn,Fam. Hypertrophic Cardiomyopathy,I42.2,2 year old male presents to the emergency depa...
150,183,Student.120,Student.120@vcom.edu,Virginia,Ischemic Cardiomyopathy,I25.2,She's a 62 year old female who presents to the...
151,976,Student.224,Student.224@vcom.edu,Auburn,Ischemic Cardiomyopathy,I25.2,Missus Leslie is a 62 year old female patient ...
152,67,Student.404,Student.404@vcom.edu,Carolinas,Acute Viral Myocarditis,I51.4,So I just met with Leslie Palmer. She is a 62 ...
153,806,Student.43,Student.43@vcom.edu,Virginia,Acute Viral Myocarditis,I51.4,"Palmer. Patient presents with, shortness of br..."

In [20]:
data_simIQ.to_csv('Simulated Data.csv',index=False)